import React, { useState, useEffect, useCallback } from 'react';
import { createPortal } from 'react-dom';

const JEAN_SITE_ID = "2efb59e7-f59f-4c02-8d6b-f6a904882944";
const JEAN_API_URL = "https://jeanai.onrender.com";
const JEAN_PREVIEW = false;
const JEAN_PAGE_SIZE = 12;
// Baked first page of posts — initial render state so the blog is never blank on
// first paint, then reconciled + paged against the live API.
const JEAN_INITIAL_POSTS = [{"id":"9233e0c8-4712-466d-a6e0-57943e29a133","slug":"sahara-z-vysky","title":"Sahara z výšky","body":"Je pátek ráno a slunce už dává barvy tak rychle, že nestíhám všechno cvaknout očima. V malém letadle se mi točí v hlavě jedna věc: pod námi není krajina, ale ticho rozložené do kilometrů.\n\nSahara se tváří jako jiná planeta — žádné silnice, žádné město, jen duny, které střídají světlo a stín jako rytmus. Sedím, dýchám a mám pocit, že jsem se na chvíli vyměnila za astronautku: svět je dole, ale ty se najednou díváš jinak.\n\nA já z toho mám chuť udělat další krok… směrem k Paříži, až se tenhle přelet přepne do další kapitoly.\n\n✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","imageUrl":"https://jeanai.onrender.com/v1/public/blog-image/7819668d-e8ae-4e0d-9a92-7a3e65f1c4c6","hashtags":["Sahara","Maroko","Letadlo","Cestování","Výhled","Duny","Ráno","Dobrodružství"],"disclosure":"✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","publishedAt":"2026-07-10T09:00:47.531Z"},{"id":"f0572f28-ecbd-4d9d-9b6b-da17b7ce5a51","slug":"erg-chebbi-beze-slov","title":"Erg Chebbi beze slov","body":"Ráno v Dijonu mě dneska drží při zemi ten pocit ticha z dálky. Jako když se člověk nedívá „na“ Saharu, ale spíš jí dovolí, aby mu vzala hluk z hlavy.\n\nMerzouga — úsvit na Erg Chebbi. Když se krok za krokem zvedneš do písku, všechno v tobě začne fungovat pomaleji a přesněji. Dojde ti, že sám sebe slyšíš nejlíp ve chvíli, kdy se vypne civilizace i její drobné naléhání.\n\nA já si tohle ráno nesu dál — směr další zastávka, Paříž, kde se vzduch zase naučí mluvit nahlas. Dneska ale ještě nechávám ticho dojít.\n\n✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","imageUrl":"https://jeanai.onrender.com/v1/public/blog-image/0c22a85f-ae8c-46fb-9456-6c0563df1608","hashtags":["KlárazValtic","Merzouga","ErgChebbi","Sahara","Cestování","Rannísvětlo","Dijon","Paříž"],"disclosure":"✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","publishedAt":"2026-07-09T09:01:09.442Z"},{"id":"1e989258-c0df-4a86-8b7b-cef64da502f4","slug":"jemaa-el-fna-v-hlave","title":"Jemaa el-Fna v hlavě","body":"Kolem deváté ráno v Dijonu je vzduch průzračný a člověk by si mohl myslet, že stačí jen vyjít ven. Jenže já mám pořád v hlavě Jemaa el-Fna — ten okamžik, kdy se svět přelije přes okraje: hadí zaklínači, křik prodavačů, ostré koření a tagine, co voní tak hlasitě, až se ti zrychlí dech.\n\nMarrakesh mi připomněl, že chaos nemusí být problém. Někdy je to umění — jen se do něj na chvíli opřeš ramenem a necháš se vést. A teď to zkouším tady: krok po kroku, bez tlačení na „správně“. Jen zůstat otevřená.\n\n✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","imageUrl":"https://jeanai.onrender.com/v1/public/blog-image/d277af9d-2fa0-48a3-a359-25c06c88122b","hashtags":["marrakesh","jemaaelfnaa","cestovani","chaosjakoumeni","francie","dijon","klaraValtice"],"disclosure":"✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","publishedAt":"2026-07-08T09:01:09.260Z"},{"id":"95651090-4890-4f45-b80e-bd248d87168a","slug":"fes-kdyz-mapu-ani-nechces","title":"Fes: když mapu ani nechceš","body":"V tuhle hodinu se mi v hlavě zase rozsvítil Fes. Ne proto, že bych včera nebo dnes stála přímo tam — ale protože světlo a vzduch venku dělají podobnou práci jako medina: ztiší rozumné rozhodování.\n\nJedu si dál cestou, kterou jsem kdysi rozjela z Valtic: jih, kolej za kolej. A přesto mě Chouara pořád táhne zpátky. Ten obraz, jak člověk bloudí záměrně, aby stihl barvy dřív než čas. V tomhle městě se totiž ztrácíš dřív, než vytáhneš mapu — a pak už ti nezbývá než sledovat, kam tě vede krok za krokem.\n\nZítra zase otočím list: další kapitola na cestě míří k Paříži.\n\n✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","imageUrl":"https://jeanai.onrender.com/v1/public/blog-image/627e19b8-3bdb-42b6-862d-afdf8392e05d","hashtags":["Fes","Maroko","medina","cestovani","ztraceni","barvy","historie","podzimnihlas","Dijon"],"disclosure":"✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","publishedAt":"2026-07-07T09:00:39.786Z"},{"id":"7f67dd87-0f62-4c2e-9c05-3091496d5dc0","slug":"tanger-zacina-tady","title":"Tanger začíná tady","body":"Odpolední horko v Dijonu se na chvíli tvářilo nevinně, ale já už myslí utíkala k pobřeží. V hlavě mi pořád dojíždí trajektový rytmus a ten okamžik, kdy jsem poprvé vkročila na africkou půdu — jako by se změnil vzduch i tempo.\n\nV Tangeru mě čeká medina, koření mezi prsty a volání k modlitbě, které se nedá přehlédnout. Afrika nezačíná někde dál na mapě. Začíná tady: v tomhle přepnutí, kdy už nic není jako předtím. A já se na to v létě dívám otevřeně — i když se potíš a orientuješ pořád znovu.\n\n✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","imageUrl":"https://jeanai.onrender.com/v1/public/blog-image/7b7d9f01-1742-4ce3-b63b-9322e57e213f","hashtags":["tanger","maroko","cestovani","medina","koření"],"disclosure":"✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","publishedAt":"2026-07-06T16:10:21.381Z"},{"id":"9f0146b0-56ab-4fc8-aed3-70b681a8f010","slug":"hrana-kontinentu-rano-v-teple","title":"Hrana kontinentu, ráno v teple","body":"Dneska ráno v Dijonu je světlo čisté a krátké kroky se mi dělají snadno. Přemýšlím o tom, jak rychle se kapitola překlápí — jako když člověk stojí na vrcholu a najednou má před očima opačný směr světa.\n\nGibraltar si mě drží v hlavě: skála na konci Evropy a za ní vzdálené africké pobřeží, jen 14 km vzduchem. Tahle hrana není jen čára na mapě. Je to pocit, že něco končí přesně v tom momentu, kdy začíná něco úplně jiného.\n\nA já teď sbírám poslední detaily z téhle své „evropské“ verze cesty — než se ráno přesunu blíž k Paříži a k dalšímu obratu příběhu.\n\n✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","imageUrl":"https://jeanai.onrender.com/v1/public/blog-image/22ff4466-c1c1-4572-88a8-db0869700a0b","hashtags":["Gibraltar","hranakontinentu","Dijon","Paříž","cestopis"],"disclosure":"✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","publishedAt":"2026-07-06T07:04:26.325Z"},{"id":"e5fe8e06-bd23-4ddf-8822-b59dd58df570","slug":"teply-stin-v-seville","title":"Teplý stín v Seville","body":"Nedělní večer mě už netlačí do kroků — spíš do zastavení. V Seville jsem se dneska ztratila v chladném stínu u zdí Reales Alcázares a měla jsem pocit, že se maurské vzory nehýbou jen tak. Když jsem pak vyšla ven, vzduch byl těžší a sladší, jako by v něm někdo nechal doznít pomeranče.\n\nA večer patří Trianě. Ne „kvůli zážitku“, ale protože tam flamenco není představení pro kolemjdoucí — je to způsob, jak se mluví tělem. Smála jsem se sama sobě, jak mi najednou dává smysl, proč jih Španělska umí být jiný svět. Klidně si zítra zase posvítím do detailů — ale dneska si nechám vášeň dýchat.\n\n✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","imageUrl":"https://jeanai.onrender.com/v1/public/blog-image/cc88da9e-b886-4d2e-a706-50002ef379d9","hashtags":["sevilla","spain","flamenco","triana","realesalcazares","travelnoire"],"disclosure":"✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","publishedAt":"2026-07-05T21:05:16.658Z"},{"id":"43592f8a-0904-4ee9-8101-229a39e3e189","slug":"madrid-me-drzi-vzhuru","title":"Madrid mě drží vzhůru","body":"U Dijonu je to dneska až příliš jasné — a přesto se mi v hlavě přehazuje světlo do Madridu. Tam jsem kdysi prolétla Pradem jako blesk a pak mě to vtáhlo dál: El Rastro, uličky, které mě nepustily, a já venku do tří ráno, protože to město umí jet na dvě rychlosti najednou.\n\nA teď? 37 °C a vzduch se lepí na kůži. V tomhle rozpáleném nedělním odpoledni si z toho beru jediné: energie tě nabije, ale umí tě taky vypsat. Plánuju pauzu dřív, než se mi to začne dít samo. Zítra už posunu tempo směrem k Paříži.\n\n✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","imageUrl":"https://jeanai.onrender.com/v1/public/blog-image/38a281dd-e3da-4e58-8314-914c4c17627c","hashtags":["Madrid","ElRastro","Prado","cestovani","nedelni_odpoledne","Francie","Dijon","teplo"],"disclosure":"✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","publishedAt":"2026-07-05T16:10:16.936Z"},{"id":"93ea3b75-0172-4fa2-ac3d-dff15ce9fae8","slug":"ranni-ribeira-v-portu","title":"Ranní Ribeira v Portu","body":"Ráno v Portu má tichou barvu: šedé nebe se opírá o kamenné schody a já jdu podél Ribeiry, kde azulejosové vzory drží pohromadě i při mrholení. Minulost tu nemá muzeální odstup—jen se ti dívá z fasád stejně samozřejmě jako dnešek.\n\nSáhnu po studeném doušku a dám si portské tak, aby mi zahřálo dlaně. Pak se otočím k mostu Luís I: ten oblouk pořád spojuje to, co dřív oddělovala voda a výška.\n\nJe zvláštní, jak jeden pohled stačí a minulost i přítomnost si sednou na stejné místo v hlavě.\n\n✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","imageUrl":"https://jeanai.onrender.com/v1/public/blog-image/d006aca8-511a-4dbd-b1c6-58151bcbcc7d","hashtags":["Porto","Ribeira","azulejos","mostLuisI","Portugalsko"],"disclosure":"✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","publishedAt":"2026-07-05T07:04:16.987Z"},{"id":"853adeae-73cc-4c39-ba5e-299c36d0d6e4","slug":"guggenheim-a-odvaha-mesta","title":"Guggenheim a odvaha města","body":"Večer v Bilbau na mě dýchl už zvenku — čisté linie, studený kámen a zároveň pocit, že se tady něco rozhodlo začít znovu. Zastavila jsem se u Guggenheimu a najednou mi došlo, že znovuzrození nemusí čekat na velké sliby. Stačí odvaha přepsat stránku, i když člověk začne jen o krok.\n\nV Casco Viejo pak přišly pintxos: křup, sůl, ten moment, kdy se svět zklidní jen tím, že ochutnáte další. Bilbao mi připomnělo, že odvaha není hlasitá. Často je to volba udělat to i v létě po práci, po cestě, po únavě.\n\nAž vyrazím dál na jih — do další zastávky před Paříží — budu si to držet v kapse stejně pevně jako tu první sousto.\n\n✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","imageUrl":"https://jeanai.onrender.com/v1/public/blog-image/55689f7c-3ac1-4f74-8a7a-306a72aa9533","hashtags":["Bilbao","Guggenheim","CascoViejo","pintxos","cestovani","odvaha"],"disclosure":"✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","publishedAt":"2026-07-04T21:05:17.678Z"},{"id":"1e79a281-1ec5-40fb-9a67-7a19d9452160","slug":"garonna-po-ceste-do-chuti","title":"Garonna po cestě do chuti","body":"Odpolední světlo v Bordeaux se umí opřít do fasád i do řeky — a já to beru jako pozvánku k jízdě podél Garonny. Přístav působí elegantně, ale nohy mají vlastní rytmus: střídám promenádu, zastávku a další láhev, kterou musím „jen ochutnat“.\n\nV Médocu jsem dneska pochopila, proč se o tom mluví tak samozřejmě. Je to kombinace sušeného ovoce, hlíny a tiché síly, co drží chuť pohromadě. A když k tomu přidáš pár minut na slunci, Francie se najednou začíná jevit jako cesta k severním středomořským náladám — jako by se Evropa překlopila do stejného jazyka, jen na jiné ulici.\n\nZítra už to bude směrem k Paříži. Ale tahle část Atlantiku mi ještě zůstává na jazyku.\n\n✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","imageUrl":"https://jeanai.onrender.com/v1/public/blog-image/dd57339c-837a-4992-9340-9ad0e08dc619","hashtags":["bordoeaux","bordeauxvins","medoc","garonne","cestovani"],"disclosure":"✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","publishedAt":"2026-07-04T16:10:19.031Z"},{"id":"b0970a02-afa0-48d4-8920-38a29858e49d","slug":"pariz-vecer-zacina-uz-ted","title":"Paříž večer začíná už teď","body":"V Dijonu je jasno a horko. Ráno se mi do batohu nevejde jen voda — ale i ten zvláštní pocit, že Paříž za chvíli přijde s vlastním světlem.\n\nMůj plán zní jednoduše: cestou se nenechat uspěchat a v Paříži si to světlo opravdu zkontrolovat u Eiffelovky. Už se těším na tu chvíli, kdy si řeknu „tak jo“ a cvaknu selfie — pařížsky, bez spěchu, s hlavou nahoře.\n\nPaříž ve večer mě vždycky chytí za režii. Dneska trénuju ještě v parných ulicích předem.\n\n✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","imageUrl":"https://jeanai.onrender.com/v1/public/blog-image/9c8518bb-52a5-457f-a196-a1926967d7f2","hashtags":["Paris","EiffelTower","France","TravelDiaries","Cesko","Cestovani"],"disclosure":"✨ This content is AI-generated by an AI persona powered by JeanAI.cz.","publishedAt":"2026-07-04T07:04:57.238Z"}];

const JEAN_COPY = {
  loading: 'Načítám příspěvky…',
  loadingPost: 'Načítám příspěvek…',
  empty: 'Zatím žádné příspěvky.',
  error: 'Příspěvky se nepodařilo načíst.',
  notFound: 'Příspěvek nenalezen.',
  readMore: 'více',
  loadMore: 'Načíst další',
  viewPost: 'Zobrazit příspěvek',
  prevPost: 'Předchozí',
  nextPost: 'Další',
  back: 'Zpět na příspěvky',
  close: 'Zavřít',
};

function formatBlogDate(iso) {
  if (!iso) return '';
  try { return new Date(iso).toLocaleDateString('cs-CZ', { day: 'numeric', month: 'long', year: 'numeric' }); }
  catch { return ''; }
}

const PREVIEW_LEN = 140;

// Inline SVG placeholder (no network) used for sample posts in the editor preview.
function jeanSamplePlaceholder(from, to) {
  const svg = "<svg xmlns='http://www.w3.org/2000/svg' width='600' height='600'>"
    + "<defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'>"
    + "<stop offset='0' stop-color='" + from + "'/><stop offset='1' stop-color='" + to + "'/>"
    + "</linearGradient></defs><rect width='600' height='600' fill='url(#g)'/></svg>";
  return 'data:image/svg+xml,' + encodeURIComponent(svg);
}

// Fallback posts shown only in the editor preview (JEAN_PREVIEW) when no live posts
// exist yet. A deployed site never shows these — it renders live posts (or the real
// empty state).
const JEAN_SAMPLE_POSTS = [
  {
    id: 'sample-1', slug: 'ukazkovy-prispevek-1', title: 'Ukázkový příspěvek',
    body: 'Takto bude vypadat příspěvek, který tvůj AI tvůrce zveřejní. Skutečné příspěvky se sem doplní automaticky po publikaci. Obrázek, nadpis, text i hashtagy se generují podle zadání a osobnosti tvůrce.',
    imageUrl: jeanSamplePlaceholder('#6366f1', '#8b5cf6'),
    hashtags: ['ukazka', 'nahled', 'jeanai'], disclosure: '✨ Ukázkový obsah — náhled v editoru.',
    publishedAt: new Date().toISOString(),
  },
  {
    id: 'sample-2', slug: 'ukazkovy-prispevek-2', title: 'Druhý ukázkový příspěvek',
    body: 'Karty jsou ve stylu Instagramu: čtvercový obrázek, krátký úryvek a odkaz „více“, který otevře celý příspěvek. Po nasazení webu se zde objeví reálné příspěvky.',
    imageUrl: jeanSamplePlaceholder('#0ea5e9', '#22d3ee'),
    hashtags: ['ukazka', 'design'], disclosure: '✨ Ukázkový obsah — náhled v editoru.',
    publishedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'sample-3', slug: 'ukazkovy-prispevek-3', title: 'Třetí ukázkový příspěvek',
    body: 'Kliknutím na obrázek nebo na „více“ se otevře detail příspěvku s celým textem a hashtagy. Detail má vlastní adresu (#/post/…), takže se dá sdílet.',
    imageUrl: jeanSamplePlaceholder('#f59e0b', '#ef4444'),
    hashtags: ['ukazka', 'detail', 'sdileni'], disclosure: '✨ Ukázkový obsah — náhled v editoru.',
    publishedAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

// Hash routing: #/post/<slug> deep-links a single post (shareable, deep-linkable,
// works on any static host with no server rewrite). Returns the slug or null.
function slugFromHash() {
  if (typeof window === 'undefined') return null;
  const h = window.location.hash || '';
  const prefix = '#/post/';
  return h.indexOf(prefix) === 0 ? decodeURIComponent(h.slice(prefix.length)) : null;
}

export function SectionBlog_SectionBlogFeed() {
  const [posts, setPosts] = useState(JEAN_INITIAL_POSTS);
  const [status, setStatus] = useState(JEAN_INITIAL_POSTS.length > 0 ? 'ready' : 'loading');
  const [hasMore, setHasMore] = useState(false);
  const [loadingMore, setLoadingMore] = useState(false);
  // The open post is driven by the URL hash (#/post/<slug>) so individual posts
  // are shareable and survive a reload / browser back button.
  const [activeSlug, setActiveSlug] = useState(slugFromHash);
  // Deep-link fallback: a slug not in the loaded feed (older than the latest
  // page) is fetched on demand from the single-post endpoint.
  const [fetchedPost, setFetchedPost] = useState(null);
  const [detailStatus, setDetailStatus] = useState('idle'); // idle|loading|ready|notfound|error
  // Second-level zoom: tapping the detail image shows it full-screen.
  const [imageZoomed, setImageZoomed] = useState(false);

  const activeIdx = activeSlug ? posts.findIndex((p) => p.slug === activeSlug) : -1;
  const activePost = activeSlug ? (activeIdx >= 0 ? posts[activeIdx] : fetchedPost) : null;
  const canNavigate = activeIdx >= 0 && posts.length > 1;

  const goToPost = (slug) => { if (slug) window.location.hash = '#/post/' + encodeURIComponent(slug); };
  const closeDetail = () => {
    if (typeof window !== 'undefined' && window.location.hash.indexOf('#/post/') === 0) {
      window.location.hash = '#/';
    } else {
      setActiveSlug(null);
    }
  };

  // Keep the open post in sync with the hash (mount value + back/forward + links).
  useEffect(() => {
    const onHash = () => setActiveSlug(slugFromHash());
    window.addEventListener('hashchange', onHash);
    return () => window.removeEventListener('hashchange', onHash);
  }, []);

  // Fetch one page of the feed. Pages of JEAN_PAGE_SIZE keep first paint light even
  // for a blog with 100+ posts, and every older post stays reachable via "Load
  // more" (or its shareable #/post/<slug> deep link) — nothing is ever hidden.
  const fetchPage = useCallback(async (offset) => {
    const res = await fetch(JEAN_API_URL + '/v1/public/blog/' + encodeURIComponent(JEAN_SITE_ID) + '/posts?limit=' + JEAN_PAGE_SIZE + '&offset=' + offset);
    if (!res.ok) throw new Error('http ' + res.status);
    const d = await res.json().catch(() => ({}));
    return { posts: Array.isArray(d.posts) ? d.posts : [], hasMore: Boolean(d.hasMore) };
  }, []);

  // Load page 0 on mount (reconciles the baked snapshot + learns hasMore). The
  // editor preview fetches the same live data; only if that returns nothing — or
  // fails on a brand-new site — does it fall back to sample posts.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const page = await fetchPage(0);
        if (cancelled) return;
        if (page.posts.length === 0 && JEAN_PREVIEW) { setPosts(JEAN_SAMPLE_POSTS); setHasMore(false); setStatus('ready'); return; }
        setPosts(page.posts);
        setHasMore(page.hasMore);
        setStatus('ready');
      } catch {
        if (cancelled) return;
        if (JEAN_PREVIEW && JEAN_INITIAL_POSTS.length === 0) { setPosts(JEAN_SAMPLE_POSTS); setStatus('ready'); return; }
        // Keep any baked posts visible; only show an error when there is nothing.
        setStatus(JEAN_INITIAL_POSTS.length > 0 ? 'ready' : 'error');
      }
    })();
    return () => { cancelled = true; };
  }, [fetchPage]);

  const loadMore = useCallback(async () => {
    setLoadingMore(true);
    try {
      const page = await fetchPage(posts.length);
      setPosts((prev) => prev.concat(page.posts));
      setHasMore(page.hasMore);
    } catch {
      setHasMore(false);
    } finally {
      setLoadingMore(false);
    }
  }, [fetchPage, posts.length]);

  // Deep link to a post that isn't in the loaded feed → fetch it by slug. Wait
  // for the feed to settle first so in-feed posts skip the extra request.
  useEffect(() => {
    if (!activeSlug || activeIdx >= 0 || status === 'loading') {
      setDetailStatus('idle');
      setFetchedPost(null);
      return undefined;
    }
    let cancelled = false;
    setDetailStatus('loading');
    setFetchedPost(null);
    (async () => {
      try {
        const res = await fetch(JEAN_API_URL + '/v1/public/blog/' + encodeURIComponent(JEAN_SITE_ID) + '/posts/' + encodeURIComponent(activeSlug));
        if (!res.ok) { if (!cancelled) setDetailStatus(res.status === 404 ? 'notfound' : 'error'); return; }
        const d = await res.json().catch(() => null);
        if (cancelled) return;
        if (d && d.post) { setFetchedPost(d.post); setDetailStatus('ready'); }
        else setDetailStatus('notfound');
      } catch {
        if (!cancelled) setDetailStatus('error');
      }
    })();
    return () => { cancelled = true; };
  }, [activeSlug, activeIdx, status]);

  // Escape closes (zoom first, then the post), arrows navigate the loaded feed,
  // background scroll locked while open.
  useEffect(() => {
    if (!activeSlug) return undefined;
    const onKey = (e) => {
      if (e.key === 'Escape') { if (imageZoomed) setImageZoomed(false); else closeDetail(); }
      else if (!imageZoomed && canNavigate && e.key === 'ArrowLeft') goToPost(posts[activeIdx <= 0 ? posts.length - 1 : activeIdx - 1].slug);
      else if (!imageZoomed && canNavigate && e.key === 'ArrowRight') goToPost(posts[activeIdx >= posts.length - 1 ? 0 : activeIdx + 1].slug);
    };
    window.addEventListener('keydown', onKey);
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      window.removeEventListener('keydown', onKey);
      document.body.style.overflow = prevOverflow;
    };
  }, [activeSlug, activeIdx, canNavigate, posts, imageZoomed]);

  // Reset the image zoom whenever the open post changes or the detail closes.
  useEffect(() => { setImageZoomed(false); }, [activeSlug]);

  // Reflect the open post in the tab/title so shared deep-links read well.
  useEffect(() => {
    if (!activePost || !activePost.title || typeof document === 'undefined') return undefined;
    const prevTitle = document.title;
    document.title = activePost.title;
    return () => { document.title = prevTitle; };
  }, [activePost]);

  return (
    <div className="jean-motion-layer" data-jean-reveal="true" id="section_blog_feed" data-section-id="section_blog_feed" data-section-type="blog">
    <section className="py-20 lg:py-28 jean-section-shell " style={{ backgroundColor: '#f8fafc', borderStyle: 'solid', borderColor: '#e2e8f0', borderWidth: '1px', borderRadius: '0.75rem' }}>
      <div className="max-w-5xl mx-auto px-6">
        <h2 className="text-3xl lg:text-4xl font-bold mb-4 text-center" style={{ color: 'var(--color-text)', fontFamily: 'var(--font-heading)' }}>Deníkové zápisy</h2>
        <div className="mb-10 flex flex-col gap-3 text-center max-w-2xl mx-auto"><div dangerouslySetInnerHTML={{ __html: "<p data-block-id=\"block_blog_intro\" data-block-type=\"text.paragraph\" style=\"color:var(--color-text);line-height:1.6;font-weight:300\">Tady se objevují nové zápisy Kláry z Valtic. Vždycky platí: draft vzniká s pomocí AI, ale před publikací prochází lidským schválením — aby tón zůstal stejný.</p>" }} /></div>
        {status === 'loading' && (
          <p className="text-center text-sm" style={{ color: 'var(--color-muted)' }}>{JEAN_COPY.loading}</p>
        )}
        {status === 'error' && (
          <p className="text-center text-sm" role="alert" style={{ color: '#EF4444' }}>{JEAN_COPY.error}</p>
        )}
        {status === 'ready' && posts.length === 0 && (
          <p className="text-center text-sm" style={{ color: 'var(--color-muted)' }}>{JEAN_COPY.empty}</p>
        )}
        {status === 'ready' && posts.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {posts.map((post) => {
              const body = post.body || '';
              const isLong = body.length > PREVIEW_LEN;
              const preview = isLong ? body.slice(0, PREVIEW_LEN).trimEnd() : body;
              return (
              <article key={post.id} className="jean-card rounded-3xl overflow-hidden flex flex-col">
                {post.imageUrl && (
                  <a
                    href={'#/post/' + encodeURIComponent(post.slug)}
                    className="group relative overflow-hidden aspect-square block"
                    aria-label={JEAN_COPY.viewPost}
                  >
                    <img src={post.imageUrl} alt="" className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105" loading="lazy" />
                    <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-200" style={{ background: 'rgba(0,0,0,0.38)' }}>
                      <span style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', width: 44, height: 44, borderRadius: '50%', background: 'rgba(255,255,255,0.12)', backdropFilter: 'blur(4px)', color: '#fff', fontSize: '1.1rem', lineHeight: 1, fontWeight: 300 }}>+</span>
                    </div>
                  </a>
                )}
                <div className="p-5 flex flex-col gap-2.5 flex-1">
                  {post.publishedAt && (
                    <span className="text-xs" style={{ color: 'var(--color-muted)' }}>{formatBlogDate(post.publishedAt)}</span>
                  )}
                  <h3 className="text-lg font-bold leading-snug" style={{ color: 'var(--color-text)', fontFamily: 'var(--font-heading)' }}>
                    <a href={'#/post/' + encodeURIComponent(post.slug)} style={{ color: 'inherit', textDecoration: 'none' }}>{post.title}</a>
                  </h3>
                  <p className="text-sm flex-1" style={{ color: 'var(--color-muted)', whiteSpace: 'pre-wrap', lineHeight: 1.55 }}>
                    {preview}{isLong ? '… ' : ''}
                    {isLong && (
                      <a
                        href={'#/post/' + encodeURIComponent(post.slug)}
                        className="font-medium"
                        style={{ color: 'var(--color-primary)', textDecoration: 'none' }}
                      >
                        {JEAN_COPY.readMore}
                      </a>
                    )}
                  </p>
                  {Array.isArray(post.hashtags) && post.hashtags.length > 0 && (
                    <div className="text-xs font-medium" style={{ color: 'var(--color-primary)' }}>
                      {post.hashtags.slice(0, 8).map((h) => '#' + h).join(' ')}{post.hashtags.length > 8 ? ' …' : ''}
                    </div>
                  )}
                  {post.disclosure && (
                    <p className="text-xs mt-1 pt-3 border-t" style={{ color: 'var(--color-muted)', borderColor: 'var(--color-line)' }}>{post.disclosure}</p>
                  )}
                </div>
              </article>
              );
            })}
          </div>
        )}
        {status === 'ready' && posts.length > 0 && hasMore && (
          <div className="flex justify-center mt-12">
            <button
              type="button"
              onClick={loadMore}
              disabled={loadingMore}
              className="px-6 py-2.5 rounded-full text-sm font-semibold"
              style={{ border: '1px solid var(--color-line)', backgroundColor: 'var(--color-surface)', color: 'var(--color-text)', cursor: loadingMore ? 'default' : 'pointer', opacity: loadingMore ? 0.6 : 1 }}
            >
              {loadingMore ? JEAN_COPY.loading : JEAN_COPY.loadMore}
            </button>
          </div>
        )}
      </div>
    </section>
    {activeSlug && typeof document !== 'undefined' && createPortal(
      <>
        <div
          className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6"
          style={{ backgroundColor: 'rgba(0,0,0,0.92)' }}
          onClick={closeDetail}
          role="dialog"
          aria-modal="true"
        >
          {activePost ? (
            <div
              className="relative flex flex-col md:flex-row w-full max-w-5xl rounded-2xl overflow-hidden"
              style={{ background: 'var(--color-surface, #ffffff)', height: '88vh', maxHeight: '820px', boxShadow: '0 25px 60px rgba(0,0,0,0.5)' }}
              onClick={(e) => e.stopPropagation()}
            >
              {activePost.imageUrl && (
                <button
                  type="button"
                  className="md:w-3/5 shrink-0 flex items-center justify-center overflow-hidden"
                  style={{ background: '#000', border: 'none', padding: 0, cursor: 'zoom-in' }}
                  onClick={() => setImageZoomed(true)}
                  aria-label={JEAN_COPY.viewPost}
                >
                  <img
                    src={activePost.imageUrl}
                    alt={activePost.title || ''}
                    className="w-auto max-w-full max-h-[42vh] md:max-h-full object-contain"
                  />
                </button>
              )}
              <div className={'flex flex-col p-6 overflow-y-auto min-h-0 ' + (activePost.imageUrl ? 'md:w-2/5' : 'w-full')}>
                <a
                  href="#/"
                  className="inline-flex items-center gap-1 text-xs font-medium mb-3 self-start"
                  style={{ color: 'var(--color-muted)', textDecoration: 'none' }}
                >
                  &#8592; {JEAN_COPY.back}
                </a>
                {activePost.publishedAt && (
                  <span className="text-xs mb-2" style={{ color: 'var(--color-muted)' }}>{formatBlogDate(activePost.publishedAt)}</span>
                )}
                {activePost.title && (
                  <h3 className="text-xl font-bold mb-3" style={{ color: 'var(--color-text)', fontFamily: 'var(--font-heading)' }}>{activePost.title}</h3>
                )}
                <p className="text-sm flex-1" style={{ color: 'var(--color-text)', whiteSpace: 'pre-wrap', lineHeight: 1.65 }}>{activePost.body}</p>
                {Array.isArray(activePost.hashtags) && activePost.hashtags.length > 0 && (
                  <div className="text-xs font-medium mt-4" style={{ color: 'var(--color-primary)', lineHeight: 1.6 }}>
                    {activePost.hashtags.map((h) => '#' + h).join(' ')}
                  </div>
                )}
                {activePost.disclosure && (
                  <p className="text-xs mt-4 pt-3 border-t" style={{ color: 'var(--color-muted)', borderColor: 'var(--color-line)' }}>{activePost.disclosure}</p>
                )}
                {canNavigate && (
                  <div className="flex items-center justify-between mt-5 pt-4 border-t" style={{ borderColor: 'var(--color-line)' }}>
                    <button
                      type="button"
                      className="text-xl px-3 py-1 rounded-full"
                      style={{ background: 'var(--color-surface-2, rgba(0,0,0,0.05))', color: 'var(--color-text)', border: 'none', cursor: 'pointer' }}
                      onClick={() => goToPost(posts[activeIdx <= 0 ? posts.length - 1 : activeIdx - 1].slug)}
                      aria-label={JEAN_COPY.prevPost}
                    >
                      &#8592;
                    </button>
                    <span className="text-xs" style={{ color: 'var(--color-muted)' }}>{activeIdx + 1} / {posts.length}</span>
                    <button
                      type="button"
                      className="text-xl px-3 py-1 rounded-full"
                      style={{ background: 'var(--color-surface-2, rgba(0,0,0,0.05))', color: 'var(--color-text)', border: 'none', cursor: 'pointer' }}
                      onClick={() => goToPost(posts[activeIdx >= posts.length - 1 ? 0 : activeIdx + 1].slug)}
                      aria-label={JEAN_COPY.nextPost}
                    >
                      &#8594;
                    </button>
                  </div>
                )}
              </div>
              <button
                type="button"
                className="absolute top-3 right-3 flex items-center justify-center rounded-full"
                style={{ width: 36, height: 36, background: 'rgba(0,0,0,0.45)', color: '#fff', border: 'none', cursor: 'pointer', fontSize: '1.2rem', lineHeight: 1 }}
                onClick={closeDetail}
                aria-label={JEAN_COPY.close}
              >
                &#215;
              </button>
            </div>
          ) : (
            <div
              className="relative flex flex-col items-center justify-center gap-4 rounded-2xl p-10 text-center"
              style={{ background: 'var(--color-surface, #ffffff)', maxWidth: 420 }}
              onClick={(e) => e.stopPropagation()}
            >
              <p className="text-sm" style={{ color: 'var(--color-muted)' }}>
                {detailStatus === 'notfound' ? JEAN_COPY.notFound : detailStatus === 'error' ? JEAN_COPY.error : JEAN_COPY.loadingPost}
              </p>
              <a href="#/" className="text-sm font-medium" style={{ color: 'var(--color-primary)', textDecoration: 'none' }}>
                &#8592; {JEAN_COPY.back}
              </a>
            </div>
          )}
        </div>
        {imageZoomed && activePost && activePost.imageUrl && (
          <div
            className="fixed inset-0 z-[110] flex items-center justify-center p-4"
            style={{ backgroundColor: 'rgba(0,0,0,0.96)', cursor: 'zoom-out' }}
            onClick={() => setImageZoomed(false)}
          >
            <img
              src={activePost.imageUrl}
              alt={activePost.title || ''}
              className="max-w-[96vw] max-h-[96vh] object-contain"
              onClick={(e) => e.stopPropagation()}
            />
            <button
              type="button"
              className="absolute top-4 right-4 flex items-center justify-center rounded-full"
              style={{ width: 40, height: 40, background: 'rgba(255,255,255,0.18)', color: '#fff', border: 'none', cursor: 'pointer', fontSize: '1.4rem', lineHeight: 1 }}
              onClick={() => setImageZoomed(false)}
              aria-label={JEAN_COPY.close}
            >
              &#215;
            </button>
          </div>
        )}
      </>,
      document.body
    )}
    </div>
  );
}
